// Mock data for matched benefits
export const mockMatchedBenefits = [
  {
    id: '1',
    beneficiary: {
      id: 'b1',
      name: 'John Doe',
      age: 12,
      gender: 'male',
      location: 'New York',
      picture: '/images/mock/beneficiary1.jpg',
      educationLevel: 'primary',
      guardianName: 'Jane Doe',
      guardianContact: '123-456-7890',
    },
    program: {
      id: 'p1',
      programName: 'After School Program',
      capacity: 30,
      ageCriteria: '10-15',
      educationLevel: 'primary',
      organization: {
        id: 'o1',
        name: 'Education First',
        location: 'New York',
      },
    },
    matchScore: 85,
    status: 'PENDING',
  },
  {
    id: '2',
    beneficiary: {
      id: 'b2',
      name: 'Alice Smith',
      age: 16,
      gender: 'female',
      location: 'Boston',
      picture: '/images/mock/beneficiary2.jpg',
      educationLevel: 'upskill',
      guardianName: 'Bob Smith',
      guardianContact: '987-654-3210',
    },
    program: {
      id: 'p2',
      programName: 'Coding Bootcamp',
      capacity: 20,
      ageCriteria: '15-18',
      educationLevel: 'upskill',
      organization: {
        id: 'o2',
        name: 'Tech Future',
        location: 'Boston',
      },
    },
    matchScore: 92,
    status: 'ACCEPTED',
  },
  {
    id: '3',
    beneficiary: {
      id: 'b3',
      name: 'Michael Johnson',
      age: 8,
      gender: 'male',
      location: 'Chicago',
      educationLevel: 'basic',
      guardianName: 'Sarah Johnson',
      guardianContact: '555-123-4567',
    },
    program: {
      id: 'p3',
      programName: 'Reading Fundamentals',
      capacity: 15,
      ageCriteria: '6-10',
      educationLevel: 'basic',
      organization: {
        id: 'o3',
        name: 'Literacy First',
        location: 'Chicago',
      },
    },
    matchScore: 78,
    status: 'PENDING',
  },
  {
    id: '4',
    beneficiary: {
      id: 'b4',
      name: 'Emily Davis',
      age: 14,
      gender: 'female',
      location: 'Los Angeles',
      picture: '/images/mock/beneficiary4.jpg',
      educationLevel: 'primary',
      guardianName: 'David Davis',
      guardianContact: '444-555-6666',
    },
    program: {
      id: 'p4',
      programName: 'STEM Workshop',
      capacity: 25,
      ageCriteria: '12-16',
      educationLevel: 'primary',
      organization: {
        id: 'o4',
        name: 'Future Scientists',
        location: 'Los Angeles',
      },
    },
    matchScore: 88,
    status: 'PENDING',
  },
  {
    id: '5',
    beneficiary: {
      id: 'b5',
      name: 'William Brown',
      age: 17,
      gender: 'male',
      location: 'Seattle',
      educationLevel: 'upskill',
      guardianName: 'Mary Brown',
      guardianContact: '777-888-9999',
    },
    program: {
      id: 'p5',
      programName: 'Digital Arts',
      capacity: 18,
      ageCriteria: '16-19',
      educationLevel: 'upskill',
      organization: {
        id: 'o5',
        name: 'Creative Futures',
        location: 'Seattle',
      },
    },
    matchScore: 65,
    status: 'REJECTED',
  },
];